defaultPlacement: end
enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  7b2005f1-de18-4004-b44d-e7ed18ae73c5: # ODC Lean Starter
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: '{% if type == ''internal'' %}news/{slug}{% endif %}'
type: channel
