fieldLayouts:
  3d213011-08d4-47e8-bd64-1cef15b4c172:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9b827383-19c5-4efe-8c36-9b1a50f55e34
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'If this image isn''t purely decorative, it should be given a short description that conveys the contents of the image for people using assistive technology. If you need help writing this text, refer to this resource: https://axesslab.com/alt-texts/.'
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 44c956fa-6d67-4ae4-9724-d9e4a27b3465
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00da6e35-ea0f-455c-8e9c-c67c1c952b28 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6ed00cb-722c-4a8c-897b-05b72b7da1ba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d5833d5-6554-42ae-9682-9d09d820c109
        userCondition: null
fs: servdGeneral
handle: general
name: General
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
