fieldLayouts:
  06756337-b5dd-49bc-99f4-ec56c70ac8f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4e3cf98-aa6f-4484-89ab-2d9339dc8458
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04085894-ffb9-4f9d-984a-0a7f282be8e8 # Job Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab9997c8-7b95-455a-a226-c4584db688bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a6cad7b-7768-49e8-9cb3-de18a0f88ae5
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 6b976f60-140d-4a53-afda-c2eddb5b1767 # Jobs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
