fieldLayouts:
  e4d45a3d-7cf5-4010-b81a-c122973fdde2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ffaaf877-764d-4f4c-abea-784060b68597
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 271f38d7-a496-44bb-869b-d5fb8dbfbe92 # Publication Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ce9c1bd-7593-4744-bf1f-43888a085829
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be3ecd43-e2ec-4d3c-8efb-9473fa1c482d # Publication Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ebe5aeb-a98d-4240-ba6a-545938ef404a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b806aad1-b7bc-41d5-90da-0f6b8115ea21 # Article Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04a7303e-b4a6-4d35-96a1-b80665259e73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05f9c6eb-8cb8-45a2-a457-c584135cbd89
        userCondition: null
handle: external
hasTitleField: true
name: External
section: 473a7662-54d9-44c8-8893-15b2bf2e10a9 # News
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
