fieldLayouts:
  a7fa58c1-1d5f-4535-b6ed-1ce756bbad97:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7029eb37-276f-43c0-94d7-813cc0ae8a08
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 15d9d7cd-ae8a-4ffe-b697-1e53a28b1a9e # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfa25b38-ea3d-4bf5-aa45-8a05b2a1967a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a8c386b-5654-47e4-b5e9-0fc113af7d09
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 67fd8ee8-edc0-4bdf-8090-281a0024761d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2282eab5-f45f-44cf-90d6-e8d1fd4d7f9b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 07a9b0c8-4d90-4a33-9ceb-b435f79c058f
        userCondition: null
handle: simple
hasTitleField: true
name: Simple
section: afd40964-7a14-497f-b9cc-5b3c76740fd4 # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
