columnSuffix: fplrwtaj
contentColumnType: string
fieldGroup: 478acdb5-bf2a-426f-8001-9111e1b6ebaf # Common
handle: horizontalAlignment
instructions: null
name: 'Horizontal Alignment'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
