columnSuffix: evbxzijk
contentColumnType: text
fieldGroup: 478acdb5-bf2a-426f-8001-9111e1b6ebaf # Common
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoImage
    - seoImageDescription
    - robots
  generalTabEnabled: '1'
  sitemapEnabledFields:
    - sitemapUrls
  sitemapTabEnabled: '1'
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
