columnSuffix: xkdizbpo
contentColumnType: text
fieldGroup: 478acdb5-bf2a-426f-8001-9111e1b6ebaf # Common
handle: telephone
instructions: null
name: Telephone
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
