columnSuffix: plnhczez
contentColumnType: string
fieldGroup: 478acdb5-bf2a-426f-8001-9111e1b6ebaf # Common
handle: verticalAlignment
instructions: null
name: 'Vertical Alignment'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - bottom
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
