childBlocks: null
conditions: null
description: ''
enabled: true
field: 15d9d7cd-ae8a-4ffe-b697-1e53a28b1a9e # Page Content
fieldLayouts:
  9d92b070-b16a-4e2e-85e6-2e92b7fb9af5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 357f30d9-8618-4d16-aaac-52246356e421 # Form
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42b6482f-92c2-45f8-a48d-23a9a1c1524b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35229c14-56b2-4763-8860-3518fd546a1e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: formReference
icon: null
ignorePermissions: true
maxBlocks: 1
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Form Reference'
sortOrder: 5
topLevel: false
