childBlocks: null
conditions: null
description: ''
enabled: true
field: 15d9d7cd-ae8a-4ffe-b697-1e53a28b1a9e # Page Content
fieldLayouts:
  6f30ce6e-53c4-4d5e-9a76-592813237995:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8b7e3524-f26a-43d9-9835-846fe991c2d3 # User Content Image
            instructions: null
            label: __blank__
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 002bfd3c-c11a-4b16-af75-d5ba9509f879
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b59bc82-0679-4231-afcd-b49f8b787969
        userCondition: null
group: null
groupChildBlockTypes: true
handle: longFormImage
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
sortOrder: 7
topLevel: false
