childBlocks: null
conditions:
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: in
        uid: 4afaacff-1ebe-4776-bc5f-e45af1f0edef
        values:
          - d82c7088-6f34-408c-ba32-30216d175651 # Home
          - 533ac4b8-6a49-4621-8fb6-0ee5e6c5751d # Default
    elementType: craft\elements\Entry
    fieldContext: global
description: ''
enabled: true
field: 15d9d7cd-ae8a-4ffe-b697-1e53a28b1a9e # Page Content
fieldLayouts:
  e25b45b6-e602-4d88-abc2-d73f6bd241f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50fed80a-0ff9-4dd4-9d18-1efc8e4c55f4 # Limit
            instructions: null
            label: 'Number of Items to Display'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c9574ef-7dab-4ba6-8923-d45cf3523c15
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: dd262531-f35e-456a-ae1f-658ac6f915e9 # Paginate
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9234c013-67f7-4d75-a1f0-7f3227c8ab64
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 2702e46c-0dad-40b9-9130-ea42593ffd2a
        userCondition: null
group: null
groupChildBlockTypes: true
handle: newsIndex
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'News Index'
sortOrder: 10
topLevel: false
