childBlocks: null
conditions:
  craft\elements\Entry:
    class: craft\elements\conditions\entries\EntryCondition
    conditionRules:
      -
        class: craft\elements\conditions\entries\TypeConditionRule
        operator: in
        uid: e006ac7e-28a3-4232-8334-3e2f28eb9133
        values:
          - d82c7088-6f34-408c-ba32-30216d175651 # Home
          - 533ac4b8-6a49-4621-8fb6-0ee5e6c5751d # Default
    elementType: craft\elements\Entry
    fieldContext: global
description: 'A manual grouping of team members'
enabled: true
field: 15d9d7cd-ae8a-4ffe-b697-1e53a28b1a9e # Page Content
fieldLayouts:
  80dc8340-cb45-4122-b6b5-0fac62ee9b18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 17b1272f-f374-4f05-9e0e-c8bb27b51854 # Plain Text
            instructions: '(for example, Leadership or Board of Directors)'
            label: 'Team Category'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e102e95-b26b-4fcc-8667-e46aa6b05a06
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc889bc4-92f6-45c1-b6f6-7b5987df6096 # Show Team Member Portraits
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f6e4214-1d36-4fc4-9038-bff2c5838bfc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df6c8ede-584d-431d-b610-c3c7efe7a778 # Team Member Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2ed83a1-e61c-4c31-b0b8-e710c793100a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c140fd5d-492d-439c-8412-19d40e79fd6e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: teamList
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Team List'
sortOrder: 12
topLevel: false
