baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'ODC Lean Starter'
primary: true
siteGroup: 38316d6a-1279-411b-9ba7-efc6af5ef122 # ODC Lean Starter
sortOrder: 1
